In [1]:
!pip install torch torchvision torchaudio

In [2]:
import torch
import numpy

# x = torch.tensor([[1,2,3]
                #  ,[4,5,6]]
                # )

# print(x.shape)
# print(x)
# y=x.view(6)
# print(y)
# print(y.shape)
# z = x.reshape(3,2)
# print(z)

In [3]:
# x = torch.tensor(2.0 , requires_grad=True)
# y = x ** 2
# z = x** 3
# print(y)

tensor(4., grad_fn=<PowBackward0>)


In [4]:
# y.backward()
# z.backward()

In [5]:
# print(x.grad)

tensor(12.)


In [6]:
x = torch.rand(3, requires_grad = True)
print(x)

tensor([0.9609, 0.9536, 0.2183], requires_grad=True)


In [7]:
y = x+2
print(y)

tensor([2.9609, 2.9536, 2.2183], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2
print(z)

v= torch.tensor([1.0,2.0,3.0] , dtype=float)

tensor([17.5341, 17.4479,  9.8417], grad_fn=<MulBackward0>)


In [11]:
z.backward(v)
print(x.grad)

tensor([11.8437, 23.6290, 26.6196])
