<a href="https://colab.research.google.com/github/anupamR27/Neural-Networks/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install torch torchvision torchaudio

In [2]:
import torch
import numpy

# x = torch.tensor([[1,2,3]
                #  ,[4,5,6]]
                # )

# print(x.shape)
# print(x)
# y=x.view(6)
# print(y)
# print(y.shape)
# z = x.reshape(3,2)
# print(z)

In [3]:
# x = torch.tensor(2.0 , requires_grad=True)
# y = x ** 2
# z = x** 3
# print(y)

In [4]:
# y.backward()
# z.backward()

In [5]:
# print(x.grad)

In [6]:
# x = torch.rand(3, requires_grad = True)
# print(x)

tensor([0.3650, 0.6735, 0.7800], requires_grad=True)


In [7]:
# y = x+2
# print(y)

tensor([2.3650, 2.6735, 2.7800], grad_fn=<AddBackward0>)


In [8]:
# z = y*y*2
# print(z)

# v= torch.tensor([1.0,2.0,3.0] , dtype=float)

tensor([11.1868, 14.2950, 15.4568], grad_fn=<MulBackward0>)


In [9]:
# z.backward(v)
# print(x.grad)

tensor([ 9.4601, 21.3878, 33.3600])


In [12]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0 , requires_grad = True)

#forward pass and compute the loss
y_hat = w*x
loss = (y_hat - y)**2
print(loss)
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
