<a href="https://colab.research.google.com/github/anupamR27/Neural-Networks/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install torch torchvision torchaudio

In [2]:
import torch
import numpy as np

# x = torch.tensor([[1,2,3]
                #  ,[4,5,6]]
                # )

# print(x.shape)
# print(x)
# y=x.view(6)
# print(y)
# print(y.shape)
# z = x.reshape(3,2)
# print(z)

In [3]:
# x = torch.tensor(2.0 , requires_grad=True)
# y = x ** 2
# z = x** 3
# print(y)

In [4]:
# y.backward()
# z.backward()

In [5]:
# print(x.grad)

In [6]:
# x = torch.rand(3, requires_grad = True)
# print(x)

tensor([0.3650, 0.6735, 0.7800], requires_grad=True)


In [7]:
# y = x+2
# print(y)

tensor([2.3650, 2.6735, 2.7800], grad_fn=<AddBackward0>)


In [8]:
# z = y*y*2
# print(z)

# v= torch.tensor([1.0,2.0,3.0] , dtype=float)

tensor([11.1868, 14.2950, 15.4568], grad_fn=<MulBackward0>)


In [9]:
# z.backward(v)
# print(x.grad)

tensor([ 9.4601, 21.3878, 33.3600])


In [12]:
# x = torch.tensor(1.0)
# y = torch.tensor(2.0)
# w = torch.tensor(1.0 , requires_grad = True)

# #forward pass and compute the loss
# y_hat = w*x
# loss = (y_hat - y)**2
# print(loss)
# loss.backward()
# print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [5]:
 # f = w * x
 # w = 2
X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8 ], dtype=np.float32)

w = 0.0

# model output
def forward(x):
  return w*x

#loss = MSE
def loss(y, y_pred):
  return ((y_pred-y)**2).mean()


# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
# y_pred = wx
def gradient(x, y, y_pred):
  return np.mean(2*x*(y_pred - y))

print(f'Prediction before training: f(5) = {forward(5):.3f}')


learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
  y_pred = forward(X)

  l = loss(Y, y_pred)

  dw = gradient(X, Y, y_pred)

  w -= learning_rate * dw # w = w - learning_rate * dw

  if epoch % 2 == 0:
    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

  print(f'Prediction after training: f(5) = {forward(5):.3f}')




Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
Prediction after training: f(5) = 1.500
Prediction after training: f(5) = 2.775
epoch 3: w = 0.772, loss = 15.66018772
Prediction after training: f(5) = 3.859
Prediction after training: f(5) = 4.780
epoch 5: w = 1.113, loss = 8.17471695
Prediction after training: f(5) = 5.563
Prediction after training: f(5) = 6.229
epoch 7: w = 1.359, loss = 4.26725292
Prediction after training: f(5) = 6.794
Prediction after training: f(5) = 7.275
epoch 9: w = 1.537, loss = 2.22753215
Prediction after training: f(5) = 7.684
Prediction after training: f(5) = 8.031
epoch 11: w = 1.665, loss = 1.16278565
Prediction after training: f(5) = 8.327
Prediction after training: f(5) = 8.578
epoch 13: w = 1.758, loss = 0.60698116
Prediction after training: f(5) = 8.791
Prediction after training: f(5) = 8.972
epoch 15: w = 1.825, loss = 0.31684780
Prediction after training: f(5) = 9.126
Prediction after training: f(5) = 9.257
epoch 17: 